dv:
  network: /hkustgz
  router: /hkustgz/f0
  keychain: "insecure"
  neighbors:
    # - uri: "udp://10.0.0.1:6363"
    # - uri: "udp://10.0.1.2:6363"
    - uri: "udp://10.0.0.1:6363"  # Points to c0
    - uri: "udp://10.0.1.2:6363"  # Points to p0
    - uri: "udp://10.0.2.2:6363"  # Points to p1
    - uri: "udp://10.0.3.2:6363"  # Points to p2
    - uri: "udp://10.0.4.2:6363"  # Points to p3
    - uri: "udp://10.0.5.2:6363"  # Points to p4
  advertise_interval: 1000
  router_dead_interval: 300000


fw:
  core:
    log_level: DEBUG
  faces:
    udp:
      enabled_unicast: true
      enabled_multicast: false
      port_unicast: 6363
      # default_mtu: 1420
    tcp:
      enabled: true
      port_unicast: 6363
    websocket:
      enabled: false
  fw:
    threads: 16
    strategy_node_name: f0