dv:
  network: /hkustgz
  router: /hkustgz/pro22
  keychain: "insecure"
  neighbors:
    - uri: "udp://172.16.0.90:6363" # Neighbor: edge22
  advertise_interval: 1000
  router_dead_interval: 300000

fw:
  core:
    log_level: DEBUG   
  faces:
    udp:
      enabled_unicast: true
      enabled_multicast: false
      port_unicast: 6363
      # default_mtu: 1420
    tcp:
      enabled: true
      port_unicast: 6363
    websocket:
      enabled: false
  fw:
    threads: 32
    strategy_node_name: pro22