dv:
  network: /hkustgz
  router: /hkustgz/con4
  keychain: "insecure"
  neighbors:
    - uri: "udp://172.16.1.26:6363" # Neighbor: core0
    - uri: "udp://172.16.1.30:6363" # Neighbor: core1
    - uri: "udp://172.16.1.34:6363" # Neighbor: core2
    - uri: "udp://172.16.1.38:6363" # Neighbor: core3
    - uri: "udp://172.16.1.42:6363" # Neighbor: core4
  advertise_interval: 1000
  router_dead_interval: 300000

fw:
  core:
    log_level: DEBUG
  faces:
    udp:
      enabled_unicast: true
      enabled_multicast: false
      port_unicast: 6363
      # default_mtu: 1420
    tcp:
      enabled: true
      port_unicast: 6363
    websocket:
      enabled: false
  fw:
    threads: 16
    strategy_node_name: con4