dv:
  network: /hkustgz
  router: /hkustgz/core1
  keychain: "insecure"
  neighbors:
    - uri: "udp://172.16.1.45:6363"  # Neighbor: core0
    - uri: "udp://172.16.1.62:6363"  # Neighbor: core2
    - uri: "udp://172.16.1.66:6363"  # Neighbor: core3
    - uri: "udp://172.16.1.70:6363"  # Neighbor: core4
    - uri: "udp://172.16.0.121:6363" # Neighbor: edge5
    - uri: "udp://172.16.0.125:6363" # Neighbor: edge6
    - uri: "udp://172.16.0.129:6363" # Neighbor: edge7
    - uri: "udp://172.16.0.133:6363" # Neighbor: edge8
    - uri: "udp://172.16.0.137:6363" # Neighbor: edge9
    - uri: "udp://172.16.0.205:6363" # Neighbor: con0
    - uri: "udp://172.16.0.225:6363" # Neighbor: con1
    - uri: "udp://172.16.0.245:6363" # Neighbor: con2
    - uri: "udp://172.16.1.9:6363"   # Neighbor: con3
    - uri: "udp://172.16.1.29:6363"  # Neighbor: con4
  advertise_interval: 1000
  router_dead_interval: 300000

fw:
  core:
    # log_level: DEBUG
  faces:
    udp:
      enabled_unicast: true
      enabled_multicast: false
      port_unicast: 6363
      # default_mtu: 1420
    tcp:
      enabled: true
      port_unicast: 6363
    websocket:
      enabled: false
  fw:
    threads: 64
    strategy_node_name: core1