dv:
  network: /hkustgz
  router: /hkustgz/core4
  keychain: "insecure"
  neighbors:
    - uri: "udp://172.16.1.57:6363"  # Neighbor: core0
    - uri: "udp://172.16.1.69:6363"  # Neighbor: core1
    - uri: "udp://172.16.1.77:6363"  # Neighbor: core2
    - uri: "udp://172.16.1.81:6363"  # Neighbor: core3
    - uri: "udp://172.16.0.181:6363" # Neighbor: edge20
    - uri: "udp://172.16.0.185:6363" # Neighbor: edge21
    - uri: "udp://172.16.0.189:6363" # Neighbor: edge22
    - uri: "udp://172.16.0.193:6363" # Neighbor: edge23
    - uri: "udp://172.16.0.197:6363" # Neighbor: edge24
    - uri: "udp://172.16.0.217:6363" # Neighbor: con0
    - uri: "udp://172.16.0.237:6363" # Neighbor: con1
    - uri: "udp://172.16.1.1:6363"   # Neighbor: con2
    - uri: "udp://172.16.1.21:6363"  # Neighbor: con3
    - uri: "udp://172.16.1.41:6363"  # Neighbor: con4
  advertise_interval: 1000
  router_dead_interval: 300000

fw:
  core:
    # log_level: DEBUG
  faces:
    udp:
      enabled_unicast: true
      enabled_multicast: false
      port_unicast: 6363
      # default_mtu: 1420
    tcp:
      enabled: true
      port_unicast: 6363
    websocket:
      enabled: false
  fw:
    threads: 64
    strategy_node_name: core4