dv:
  network: /hkustgz
  router: /hkustgz/core2
  keychain: "insecure"
  neighbors:
    - uri: "udp://172.16.0.101:6363" # Neighbor: edge10
    - uri: "udp://172.16.0.105:6363" # Neighbor: edge11
    - uri: "udp://172.16.0.109:6363" # Neighbor: edge12
    - uri: "udp://172.16.0.113:6363" # Neighbor: edge13
    - uri: "udp://172.16.0.117:6363" # Neighbor: edge14
    - uri: "udp://172.16.0.129:6363" # Neighbor: con0
    - uri: "udp://172.16.0.149:6363" # Neighbor: con1
    - uri: "udp://172.16.0.169:6363" # Neighbor: con2
    - uri: "udp://172.16.0.185:6363" # Neighbor: core0
    - uri: "udp://172.16.0.197:6363" # Neighbor: core1
    - uri: "udp://172.16.0.210:6363" # Neighbor: core3
    - uri: "udp://172.16.0.214:6363" # Neighbor: core4
  advertise_interval: 1000
  router_dead_interval: 300000

fw:
  core:
    # log_level: DEBUG
  faces:
    udp:
      enabled_unicast: true
      enabled_multicast: false
      port_unicast: 6363
      # default_mtu: 1420
    tcp:
      enabled: true
      port_unicast: 6363
    websocket:
      enabled: false
  fw:
    threads: 32
    strategy_node_name: core2