dv:
  network: /hkustgz
  router: /hkustgz/edge8
  keychain: "insecure"
  neighbors:
    - uri: "udp://172.16.0.33:6363" # Neighbor: pro8
    - uri: "udp://172.16.0.94:6363" # Neighbor: core1
  advertise_interval: 1000
  router_dead_interval: 300000

fw:
  core:
    log_level: INFO
  faces:
    udp:
      enabled_unicast: true
      enabled_multicast: false
      port_unicast: 6363
      # default_mtu: 1420
    tcp:
      enabled: true
      port_unicast: 6363
    websocket:
      enabled: false
  fw:
    threads: 32
    strategy_node_name: edge8
